/* Generated By:JavaCC: Do not edit this line. ReaderConstants.java */
package reader;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARO = 5;
  /** RegularExpression Id. */
  int PARF = 6;
  /** RegularExpression Id. */
  int CROO = 7;
  /** RegularExpression Id. */
  int CROF = 8;
  /** RegularExpression Id. */
  int CADO = 9;
  /** RegularExpression Id. */
  int CADF = 10;
  /** RegularExpression Id. */
  int DIESE = 11;
  /** RegularExpression Id. */
  int FLECHE = 12;
  /** RegularExpression Id. */
  int VIRGULE = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int PIPE = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int COMPOSANT = 19;
  /** RegularExpression Id. */
  int ETAT_ITR = 20;
  /** RegularExpression Id. */
  int ETAT_LED = 21;
  /** RegularExpression Id. */
  int COMPOSITE = 22;
  /** RegularExpression Id. */
  int ELEMENTAIRE = 23;
  /** RegularExpression Id. */
  int RECEPTEUR = 24;
  /** RegularExpression Id. */
  int GENERATEUR = 25;
  /** RegularExpression Id. */
  int TRANSFORMATEUR = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\"#\"",
    "\"->\"",
    "\",\"",
    "<NUM>",
    "<ID>",
    "\"|\"",
    "<LETTER>",
    "<DIGIT>",
    "<COMPOSANT>",
    "<ETAT_ITR>",
    "<ETAT_LED>",
    "\"Oux\"",
    "<ELEMENTAIRE>",
    "\"Led\"",
    "<GENERATEUR>",
    "<TRANSFORMATEUR>",
  };

}
